# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aaaa.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog, QFileDialog
from collections import OrderedDict
import serial

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, -20, 781, 571))
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.iKinBtn = QtWidgets.QPushButton(self.mainPage)
        self.iKinBtn.setGeometry(QtCore.QRect(220, 210, 321, 71))
        self.iKinBtn.setStyleSheet("font: 75 25pt \"Helvetica\";")
        self.iKinBtn.setObjectName("iKinBtn")
        self.angBtn = QtWidgets.QPushButton(self.mainPage)
        self.angBtn.setGeometry(QtCore.QRect(220, 360, 321, 71))
        self.angBtn.setStyleSheet("font: 75 25pt \"Helvetica\";")
        self.angBtn.setObjectName("angBtn")
        self.mainLabel = QtWidgets.QLabel(self.mainPage)
        self.mainLabel.setGeometry(QtCore.QRect(130, 40, 521, 141))
        self.mainLabel.setStyleSheet("font: 48pt \".SF NS Text\";")
        self.mainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mainLabel.setObjectName("mainLabel")
        self.stackedWidget.addWidget(self.mainPage)
        self.iKinPage = QtWidgets.QWidget()
        self.iKinPage.setObjectName("iKinPage")
        self.stateCombo = QtWidgets.QComboBox(self.iKinPage)
        self.stateCombo.setGeometry(QtCore.QRect(690, 320, 81, 21))
        self.stateCombo.setObjectName("stateCombo")
        self.stateCombo.addItem("")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.iKinPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 681, 533))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("font: 28pt \".SF NS Text\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(3, 3, 3, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(10, 3, 3, 3)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lXLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lXLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lXLabel.setObjectName("lXLabel")
        self.horizontalLayout_14.addWidget(self.lXLabel)
        self.lXSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.lXSpin.setDecimals(3)
        self.lXSpin.setMinimum(-1000.0)
        self.lXSpin.setMaximum(1000.0)
        self.lXSpin.setObjectName("lXSpin")
        self.horizontalLayout_14.addWidget(self.lXSpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lYLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lYLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lYLabel.setObjectName("lYLabel")
        self.horizontalLayout_13.addWidget(self.lYLabel)
        self.lYSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.lYSpin.setDecimals(3)
        self.lYSpin.setMinimum(-1000.0)
        self.lYSpin.setMaximum(1000.0)
        self.lYSpin.setObjectName("lYSpin")
        self.horizontalLayout_13.addWidget(self.lYSpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lZLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lZLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lZLabel.setObjectName("lZLabel")
        self.horizontalLayout_12.addWidget(self.lZLabel)
        self.lZSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.lZSpin.setDecimals(3)
        self.lZSpin.setMinimum(-1000.0)
        self.lZSpin.setMaximum(1000.0)
        self.lZSpin.setObjectName("lZSpin")
        self.horizontalLayout_12.addWidget(self.lZSpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lRollLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lRollLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lRollLabel.setObjectName("lRollLabel")
        self.horizontalLayout_11.addWidget(self.lRollLabel)
        self.lRollSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.lRollSpin.setDecimals(3)
        self.lRollSpin.setMinimum(-1000.0)
        self.lRollSpin.setMaximum(1000.0)
        self.lRollSpin.setObjectName("lRollSpin")
        self.horizontalLayout_11.addWidget(self.lRollSpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lPitchLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lPitchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lPitchLabel.setObjectName("lPitchLabel")
        self.horizontalLayout_10.addWidget(self.lPitchLabel)
        self.lPitchSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.lPitchSpin.setDecimals(3)
        self.lPitchSpin.setMinimum(-1000.0)
        self.lPitchSpin.setMaximum(1000.0)
        self.lPitchSpin.setObjectName("lPitchSpin")
        self.horizontalLayout_10.addWidget(self.lPitchSpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lYawLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lYawLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lYawLabel.setObjectName("lYawLabel")
        self.horizontalLayout_9.addWidget(self.lYawLabel)
        self.lYawSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.lYawSpin.setDecimals(3)
        self.lYawSpin.setMinimum(-1000.0)
        self.lYawSpin.setMaximum(1000.0)
        self.lYawSpin.setObjectName("lYawSpin")
        self.horizontalLayout_9.addWidget(self.lYawSpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rXLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rXLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rXLabel.setObjectName("rXLabel")
        self.horizontalLayout_8.addWidget(self.rXLabel)
        self.rXSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.rXSpin.setDecimals(3)
        self.rXSpin.setMinimum(-1000.0)
        self.rXSpin.setMaximum(1000.0)
        self.rXSpin.setObjectName("rXSpin")
        self.horizontalLayout_8.addWidget(self.rXSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rYLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rYLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rYLabel.setObjectName("rYLabel")
        self.horizontalLayout_7.addWidget(self.rYLabel)
        self.rYSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.rYSpin.setDecimals(3)
        self.rYSpin.setMinimum(-1000.0)
        self.rYSpin.setMaximum(1000.0)
        self.rYSpin.setObjectName("rYSpin")
        self.horizontalLayout_7.addWidget(self.rYSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.rZLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rZLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rZLabel.setObjectName("rZLabel")
        self.horizontalLayout_6.addWidget(self.rZLabel)
        self.rZSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.rZSpin.setDecimals(3)
        self.rZSpin.setMinimum(-1000.0)
        self.rZSpin.setMaximum(1000.0)
        self.rZSpin.setObjectName("rZSpin")
        self.horizontalLayout_6.addWidget(self.rZSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rRollLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rRollLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rRollLabel.setObjectName("rRollLabel")
        self.horizontalLayout_5.addWidget(self.rRollLabel)
        self.rRollSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.rRollSpin.setDecimals(3)
        self.rRollSpin.setMinimum(-1000.0)
        self.rRollSpin.setMaximum(1000.0)
        self.rRollSpin.setObjectName("rRollSpin")
        self.horizontalLayout_5.addWidget(self.rRollSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rPitchLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rPitchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rPitchLabel.setObjectName("rPitchLabel")
        self.horizontalLayout_3.addWidget(self.rPitchLabel)
        self.rPitchSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.rPitchSpin.setDecimals(3)
        self.rPitchSpin.setMinimum(-1000.0)
        self.rPitchSpin.setMaximum(1000.0)
        self.rPitchSpin.setObjectName("rPitchSpin")
        self.horizontalLayout_3.addWidget(self.rPitchSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rYawLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rYawLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rYawLabel.setObjectName("rYawLabel")
        self.horizontalLayout_4.addWidget(self.rYawLabel)
        self.rYawSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.rYawSpin.setDecimals(3)
        self.rYawSpin.setMinimum(-1000.0)
        self.rYawSpin.setMaximum(1000.0)
        self.rYawSpin.setObjectName("rYawSpin")
        self.horizontalLayout_4.addWidget(self.rYawSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.lAPitchLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lAPitchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lAPitchLabel.setObjectName("lAPitchLabel")
        self.horizontalLayout_26.addWidget(self.lAPitchLabel)
        self.lAPitchSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.lAPitchSpin.setDecimals(3)
        self.lAPitchSpin.setMinimum(-1000.0)
        self.lAPitchSpin.setMaximum(1000.0)
        self.lAPitchSpin.setObjectName("lAPitchSpin")
        self.horizontalLayout_26.addWidget(self.lAPitchSpin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.lARollLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lARollLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lARollLabel.setObjectName("lARollLabel")
        self.horizontalLayout_25.addWidget(self.lARollLabel)
        self.lARollSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.lARollSpin.setDecimals(3)
        self.lARollSpin.setMinimum(-1000.0)
        self.lARollSpin.setMaximum(1000.0)
        self.lARollSpin.setObjectName("lARollSpin")
        self.horizontalLayout_25.addWidget(self.lARollSpin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.lAElbowLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lAElbowLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lAElbowLabel.setObjectName("lAElbowLabel")
        self.horizontalLayout_24.addWidget(self.lAElbowLabel)
        self.lAElbowSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.lAElbowSpin.setDecimals(3)
        self.lAElbowSpin.setMinimum(-1000.0)
        self.lAElbowSpin.setMaximum(1000.0)
        self.lAElbowSpin.setObjectName("lAElbowSpin")
        self.horizontalLayout_24.addWidget(self.lAElbowSpin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.lAVpLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lAVpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lAVpLabel.setObjectName("lAVpLabel")
        self.horizontalLayout_23.addWidget(self.lAVpLabel)
        self.lAVpSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.lAVpSpin.setDecimals(3)
        self.lAVpSpin.setMinimum(-1000.0)
        self.lAVpSpin.setMaximum(1000.0)
        self.lAVpSpin.setObjectName("lAVpSpin")
        self.horizontalLayout_23.addWidget(self.lAVpSpin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.lAVrLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lAVrLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lAVrLabel.setObjectName("lAVrLabel")
        self.horizontalLayout_21.addWidget(self.lAVrLabel)
        self.lAVrSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.lAVrSpin.setDecimals(3)
        self.lAVrSpin.setMinimum(-1000.0)
        self.lAVrSpin.setMaximum(1000.0)
        self.lAVrSpin.setObjectName("lAVrSpin")
        self.horizontalLayout_21.addWidget(self.lAVrSpin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.lAVeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lAVeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lAVeLabel.setObjectName("lAVeLabel")
        self.horizontalLayout_22.addWidget(self.lAVeLabel)
        self.lAVeSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.lAVeSpin.setDecimals(3)
        self.lAVeSpin.setMinimum(-1000.0)
        self.lAVeSpin.setMaximum(1000.0)
        self.lAVeSpin.setObjectName("lAVeSpin")
        self.horizontalLayout_22.addWidget(self.lAVeSpin)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.rAPitchLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rAPitchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rAPitchLabel.setObjectName("rAPitchLabel")
        self.horizontalLayout_20.addWidget(self.rAPitchLabel)
        self.rAPitchSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.rAPitchSpin.setDecimals(3)
        self.rAPitchSpin.setMinimum(-1000.0)
        self.rAPitchSpin.setMaximum(1000.0)
        self.rAPitchSpin.setObjectName("rAPitchSpin")
        self.horizontalLayout_20.addWidget(self.rAPitchSpin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.rARollLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rARollLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rARollLabel.setObjectName("rARollLabel")
        self.horizontalLayout_19.addWidget(self.rARollLabel)
        self.rARollSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.rARollSpin.setDecimals(3)
        self.rARollSpin.setMinimum(-1000.0)
        self.rARollSpin.setMaximum(1000.0)
        self.rARollSpin.setObjectName("rARollSpin")
        self.horizontalLayout_19.addWidget(self.rARollSpin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.rAElbowLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rAElbowLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rAElbowLabel.setObjectName("rAElbowLabel")
        self.horizontalLayout_18.addWidget(self.rAElbowLabel)
        self.rAElbowSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.rAElbowSpin.setDecimals(3)
        self.rAElbowSpin.setMinimum(-1000.0)
        self.rAElbowSpin.setMaximum(1000.0)
        self.rAElbowSpin.setObjectName("rAElbowSpin")
        self.horizontalLayout_18.addWidget(self.rAElbowSpin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.rAVpLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rAVpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rAVpLabel.setObjectName("rAVpLabel")
        self.horizontalLayout_17.addWidget(self.rAVpLabel)
        self.rAVpSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.rAVpSpin.setDecimals(3)
        self.rAVpSpin.setMinimum(-1000.0)
        self.rAVpSpin.setMaximum(1000.0)
        self.rAVpSpin.setObjectName("rAVpSpin")
        self.horizontalLayout_17.addWidget(self.rAVpSpin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.rAVrLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rAVrLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rAVrLabel.setObjectName("rAVrLabel")
        self.horizontalLayout_15.addWidget(self.rAVrLabel)
        self.rAVrSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.rAVrSpin.setDecimals(3)
        self.rAVrSpin.setMinimum(-1000.0)
        self.rAVrSpin.setMaximum(1000.0)
        self.rAVrSpin.setObjectName("rAVrSpin")
        self.horizontalLayout_15.addWidget(self.rAVrSpin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.rAVeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rAVeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rAVeLabel.setObjectName("rAVeLabel")
        self.horizontalLayout_16.addWidget(self.rAVeLabel)
        self.rAVeSpin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.rAVeSpin.setDecimals(3)
        self.rAVeSpin.setMinimum(-1000.0)
        self.rAVeSpin.setMaximum(1000.0)
        self.rAVeSpin.setObjectName("rAVeSpin")
        self.horizontalLayout_16.addWidget(self.rAVeSpin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.delayFrame = QtWidgets.QFrame(self.iKinPage)
        self.delayFrame.setGeometry(QtCore.QRect(690, 130, 91, 81))
        self.delayFrame.setStyleSheet("")
        self.delayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.delayFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.delayFrame.setObjectName("delayFrame")
        self.delayLabel = QtWidgets.QLabel(self.delayFrame)
        self.delayLabel.setGeometry(QtCore.QRect(10, 10, 61, 28))
        self.delayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.delayLabel.setObjectName("delayLabel")
        self.delaySpin = QtWidgets.QSpinBox(self.delayFrame)
        self.delaySpin.setGeometry(QtCore.QRect(10, 50, 71, 24))
        self.delaySpin.setMaximum(1000)
        self.delaySpin.setObjectName("delaySpin")
        self.counterFrame = QtWidgets.QFrame(self.iKinPage)
        self.counterFrame.setGeometry(QtCore.QRect(690, 220, 91, 80))
        self.counterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.counterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.counterFrame.setObjectName("counterFrame")
        self.counterLabel = QtWidgets.QLabel(self.counterFrame)
        self.counterLabel.setGeometry(QtCore.QRect(10, 0, 61, 28))
        self.counterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.counterLabel.setObjectName("counterLabel")
        self.counterSpin = QtWidgets.QSpinBox(self.counterFrame)
        self.counterSpin.setGeometry(QtCore.QRect(10, 40, 71, 24))
        self.counterSpin.setMaximum(1000)
        self.counterSpin.setObjectName("counterSpin")
        self.newStateBtn = QtWidgets.QPushButton(self.iKinPage)
        self.newStateBtn.setGeometry(QtCore.QRect(690, 360, 91, 32))
        self.newStateBtn.setObjectName("newStateBtn")
        self.saveBtn = QtWidgets.QPushButton(self.iKinPage)
        self.saveBtn.setGeometry(QtCore.QRect(690, 400, 91, 32))
        self.saveBtn.setObjectName("saveBtn")
        self.submitBtn = QtWidgets.QPushButton(self.iKinPage)
        self.submitBtn.setGeometry(QtCore.QRect(690, 440, 91, 32))
        self.submitBtn.setObjectName("submitBtn")
        self.stackedWidget.addWidget(self.iKinPage)
        self.angPage = QtWidgets.QWidget()
        self.angPage.setObjectName("angPage")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.angPage)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 481, 551))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_8.setSpacing(4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(200, 20, 68, 20))
        self.doubleSpinBox_3.setDecimals(3)
        self.doubleSpinBox_3.setMinimum(-1000.0)
        self.doubleSpinBox_3.setMaximum(1000.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(200, 0, 60, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.doubleSpinBox_37 = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox_37.setGeometry(QtCore.QRect(200, 20, 68, 20))
        self.doubleSpinBox_37.setDecimals(3)
        self.doubleSpinBox_37.setMinimum(-1000.0)
        self.doubleSpinBox_37.setMaximum(1000.0)
        self.doubleSpinBox_37.setObjectName("doubleSpinBox_37")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(200, 0, 60, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBox.setGeometry(QtCore.QRect(340, 10, 68, 20))
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMinimum(-1000.0)
        self.doubleSpinBox.setMaximum(1000.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(400, 10, 60, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(390, 40, 68, 20))
        self.doubleSpinBox_2.setDecimals(3)
        self.doubleSpinBox_2.setMinimum(-1000.0)
        self.doubleSpinBox_2.setMaximum(1000.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_38 = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBox_38.setGeometry(QtCore.QRect(60, 10, 68, 20))
        self.doubleSpinBox_38.setDecimals(3)
        self.doubleSpinBox_38.setMinimum(-1000.0)
        self.doubleSpinBox_38.setMaximum(1000.0)
        self.doubleSpinBox_38.setObjectName("doubleSpinBox_38")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 60, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.doubleSpinBox_39 = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.doubleSpinBox_39.setGeometry(QtCore.QRect(370, 10, 61, 20))
        self.doubleSpinBox_39.setDecimals(3)
        self.doubleSpinBox_39.setMinimum(-1000.0)
        self.doubleSpinBox_39.setMaximum(1000.0)
        self.doubleSpinBox_39.setObjectName("doubleSpinBox_39")
        self.doubleSpinBox_40 = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.doubleSpinBox_40.setGeometry(QtCore.QRect(40, 10, 61, 20))
        self.doubleSpinBox_40.setDecimals(3)
        self.doubleSpinBox_40.setMinimum(-1000.0)
        self.doubleSpinBox_40.setMaximum(1000.0)
        self.doubleSpinBox_40.setObjectName("doubleSpinBox_40")
        self.doubleSpinBox_41 = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.doubleSpinBox_41.setGeometry(QtCore.QRect(210, 20, 61, 20))
        self.doubleSpinBox_41.setDecimals(3)
        self.doubleSpinBox_41.setMinimum(-1000.0)
        self.doubleSpinBox_41.setMaximum(1000.0)
        self.doubleSpinBox_41.setObjectName("doubleSpinBox_41")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(0, 10, 41, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(430, 10, 41, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(210, 0, 41, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(430, 40, 41, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setGeometry(QtCore.QRect(860, 40, 41, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.doubleSpinBox_42 = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.doubleSpinBox_42.setGeometry(QtCore.QRect(640, 50, 61, 20))
        self.doubleSpinBox_42.setDecimals(3)
        self.doubleSpinBox_42.setMinimum(-1000.0)
        self.doubleSpinBox_42.setMaximum(1000.0)
        self.doubleSpinBox_42.setObjectName("doubleSpinBox_42")
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setGeometry(QtCore.QRect(640, 30, 41, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.doubleSpinBox_43 = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.doubleSpinBox_43.setGeometry(QtCore.QRect(800, 40, 61, 20))
        self.doubleSpinBox_43.setDecimals(3)
        self.doubleSpinBox_43.setMinimum(-1000.0)
        self.doubleSpinBox_43.setMaximum(1000.0)
        self.doubleSpinBox_43.setObjectName("doubleSpinBox_43")
        self.doubleSpinBox_44 = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.doubleSpinBox_44.setGeometry(QtCore.QRect(470, 40, 61, 20))
        self.doubleSpinBox_44.setDecimals(3)
        self.doubleSpinBox_44.setMinimum(-1000.0)
        self.doubleSpinBox_44.setMaximum(1000.0)
        self.doubleSpinBox_44.setObjectName("doubleSpinBox_44")
        self.verticalLayout_8.addWidget(self.frame_5)
        self.frame_7 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.doubleSpinBox_45 = QtWidgets.QDoubleSpinBox(self.frame_7)
        self.doubleSpinBox_45.setGeometry(QtCore.QRect(370, 10, 61, 20))
        self.doubleSpinBox_45.setDecimals(3)
        self.doubleSpinBox_45.setMinimum(-1000.0)
        self.doubleSpinBox_45.setMaximum(1000.0)
        self.doubleSpinBox_45.setObjectName("doubleSpinBox_45")
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setGeometry(QtCore.QRect(430, 10, 41, 20))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        self.label_13.setGeometry(QtCore.QRect(210, 0, 41, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.doubleSpinBox_46 = QtWidgets.QDoubleSpinBox(self.frame_7)
        self.doubleSpinBox_46.setGeometry(QtCore.QRect(210, 20, 61, 20))
        self.doubleSpinBox_46.setDecimals(3)
        self.doubleSpinBox_46.setMinimum(-1000.0)
        self.doubleSpinBox_46.setMaximum(1000.0)
        self.doubleSpinBox_46.setObjectName("doubleSpinBox_46")
        self.doubleSpinBox_47 = QtWidgets.QDoubleSpinBox(self.frame_7)
        self.doubleSpinBox_47.setGeometry(QtCore.QRect(40, 10, 61, 20))
        self.doubleSpinBox_47.setDecimals(3)
        self.doubleSpinBox_47.setMinimum(-1000.0)
        self.doubleSpinBox_47.setMaximum(1000.0)
        self.doubleSpinBox_47.setObjectName("doubleSpinBox_47")
        self.label_14 = QtWidgets.QLabel(self.frame_7)
        self.label_14.setGeometry(QtCore.QRect(0, 10, 41, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.doubleSpinBox_48 = QtWidgets.QDoubleSpinBox(self.frame_8)
        self.doubleSpinBox_48.setGeometry(QtCore.QRect(310, 10, 61, 20))
        self.doubleSpinBox_48.setDecimals(3)
        self.doubleSpinBox_48.setMinimum(-1000.0)
        self.doubleSpinBox_48.setMaximum(1000.0)
        self.doubleSpinBox_48.setObjectName("doubleSpinBox_48")
        self.label_15 = QtWidgets.QLabel(self.frame_8)
        self.label_15.setGeometry(QtCore.QRect(370, 10, 41, 20))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.doubleSpinBox_53 = QtWidgets.QDoubleSpinBox(self.frame_8)
        self.doubleSpinBox_53.setGeometry(QtCore.QRect(100, 10, 61, 20))
        self.doubleSpinBox_53.setDecimals(3)
        self.doubleSpinBox_53.setMinimum(-1000.0)
        self.doubleSpinBox_53.setMaximum(1000.0)
        self.doubleSpinBox_53.setObjectName("doubleSpinBox_53")
        self.label_21 = QtWidgets.QLabel(self.frame_8)
        self.label_21.setGeometry(QtCore.QRect(60, 10, 41, 20))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_8.addWidget(self.frame_8)
        self.frame_6 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.doubleSpinBox_49 = QtWidgets.QDoubleSpinBox(self.frame_6)
        self.doubleSpinBox_49.setGeometry(QtCore.QRect(310, 10, 61, 20))
        self.doubleSpinBox_49.setDecimals(3)
        self.doubleSpinBox_49.setMinimum(-1000.0)
        self.doubleSpinBox_49.setMaximum(1000.0)
        self.doubleSpinBox_49.setObjectName("doubleSpinBox_49")
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setGeometry(QtCore.QRect(370, 10, 41, 20))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.doubleSpinBox_50 = QtWidgets.QDoubleSpinBox(self.frame_6)
        self.doubleSpinBox_50.setGeometry(QtCore.QRect(350, 40, 61, 20))
        self.doubleSpinBox_50.setDecimals(3)
        self.doubleSpinBox_50.setMinimum(-1000.0)
        self.doubleSpinBox_50.setMaximum(1000.0)
        self.doubleSpinBox_50.setObjectName("doubleSpinBox_50")
        self.doubleSpinBox_56 = QtWidgets.QDoubleSpinBox(self.frame_6)
        self.doubleSpinBox_56.setGeometry(QtCore.QRect(100, 10, 61, 20))
        self.doubleSpinBox_56.setDecimals(3)
        self.doubleSpinBox_56.setMinimum(-1000.0)
        self.doubleSpinBox_56.setMaximum(1000.0)
        self.doubleSpinBox_56.setObjectName("doubleSpinBox_56")
        self.label_22 = QtWidgets.QLabel(self.frame_6)
        self.label_22.setGeometry(QtCore.QRect(60, 10, 41, 20))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_8.addWidget(self.frame_6)
        self.frame_9 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.doubleSpinBox_51 = QtWidgets.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_51.setGeometry(QtCore.QRect(310, 10, 61, 20))
        self.doubleSpinBox_51.setDecimals(3)
        self.doubleSpinBox_51.setMinimum(-1000.0)
        self.doubleSpinBox_51.setMaximum(1000.0)
        self.doubleSpinBox_51.setObjectName("doubleSpinBox_51")
        self.label_17 = QtWidgets.QLabel(self.frame_9)
        self.label_17.setGeometry(QtCore.QRect(370, 10, 41, 20))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.doubleSpinBox_57 = QtWidgets.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_57.setGeometry(QtCore.QRect(100, 10, 61, 20))
        self.doubleSpinBox_57.setDecimals(3)
        self.doubleSpinBox_57.setMinimum(-1000.0)
        self.doubleSpinBox_57.setMaximum(1000.0)
        self.doubleSpinBox_57.setObjectName("doubleSpinBox_57")
        self.label_23 = QtWidgets.QLabel(self.frame_9)
        self.label_23.setGeometry(QtCore.QRect(60, 10, 41, 20))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_8.addWidget(self.frame_9)
        self.frame_12 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_8.addWidget(self.frame_12)
        self.frame_11 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.doubleSpinBox_52 = QtWidgets.QDoubleSpinBox(self.frame_11)
        self.doubleSpinBox_52.setGeometry(QtCore.QRect(310, 10, 61, 20))
        self.doubleSpinBox_52.setDecimals(3)
        self.doubleSpinBox_52.setMinimum(-1000.0)
        self.doubleSpinBox_52.setMaximum(1000.0)
        self.doubleSpinBox_52.setObjectName("doubleSpinBox_52")
        self.label_18 = QtWidgets.QLabel(self.frame_11)
        self.label_18.setGeometry(QtCore.QRect(370, 10, 41, 20))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.doubleSpinBox_58 = QtWidgets.QDoubleSpinBox(self.frame_11)
        self.doubleSpinBox_58.setGeometry(QtCore.QRect(100, 10, 61, 20))
        self.doubleSpinBox_58.setDecimals(3)
        self.doubleSpinBox_58.setMinimum(-1000.0)
        self.doubleSpinBox_58.setMaximum(1000.0)
        self.doubleSpinBox_58.setObjectName("doubleSpinBox_58")
        self.label_24 = QtWidgets.QLabel(self.frame_11)
        self.label_24.setGeometry(QtCore.QRect(60, 10, 41, 20))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_8.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_8.addWidget(self.frame_10)
        self.frame_13 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.doubleSpinBox_54 = QtWidgets.QDoubleSpinBox(self.frame_13)
        self.doubleSpinBox_54.setGeometry(QtCore.QRect(310, 10, 61, 20))
        self.doubleSpinBox_54.setDecimals(3)
        self.doubleSpinBox_54.setMinimum(-1000.0)
        self.doubleSpinBox_54.setMaximum(1000.0)
        self.doubleSpinBox_54.setObjectName("doubleSpinBox_54")
        self.label_19 = QtWidgets.QLabel(self.frame_13)
        self.label_19.setGeometry(QtCore.QRect(370, 10, 41, 20))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.doubleSpinBox_59 = QtWidgets.QDoubleSpinBox(self.frame_13)
        self.doubleSpinBox_59.setGeometry(QtCore.QRect(100, 10, 61, 20))
        self.doubleSpinBox_59.setDecimals(3)
        self.doubleSpinBox_59.setMinimum(-1000.0)
        self.doubleSpinBox_59.setMaximum(1000.0)
        self.doubleSpinBox_59.setObjectName("doubleSpinBox_59")
        self.label_25 = QtWidgets.QLabel(self.frame_13)
        self.label_25.setGeometry(QtCore.QRect(60, 10, 41, 20))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_8.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.doubleSpinBox_55 = QtWidgets.QDoubleSpinBox(self.frame_14)
        self.doubleSpinBox_55.setGeometry(QtCore.QRect(310, 10, 61, 20))
        self.doubleSpinBox_55.setDecimals(3)
        self.doubleSpinBox_55.setMinimum(-1000.0)
        self.doubleSpinBox_55.setMaximum(1000.0)
        self.doubleSpinBox_55.setObjectName("doubleSpinBox_55")
        self.label_20 = QtWidgets.QLabel(self.frame_14)
        self.label_20.setGeometry(QtCore.QRect(370, 10, 41, 20))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.doubleSpinBox_60 = QtWidgets.QDoubleSpinBox(self.frame_14)
        self.doubleSpinBox_60.setGeometry(QtCore.QRect(100, 10, 61, 20))
        self.doubleSpinBox_60.setDecimals(3)
        self.doubleSpinBox_60.setMinimum(-1000.0)
        self.doubleSpinBox_60.setMaximum(1000.0)
        self.doubleSpinBox_60.setObjectName("doubleSpinBox_60")
        self.label_26 = QtWidgets.QLabel(self.frame_14)
        self.label_26.setGeometry(QtCore.QRect(60, 10, 41, 20))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_8.addWidget(self.frame_14)
        self.angDelayFrame = QtWidgets.QFrame(self.angPage)
        self.angDelayFrame.setGeometry(QtCore.QRect(600, 120, 91, 81))
        self.angDelayFrame.setStyleSheet("")
        self.angDelayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.angDelayFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.angDelayFrame.setObjectName("angDelayFrame")
        self.angDelayLabel = QtWidgets.QLabel(self.angDelayFrame)
        self.angDelayLabel.setGeometry(QtCore.QRect(10, 10, 61, 28))
        self.angDelayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.angDelayLabel.setObjectName("angDelayLabel")
        self.angDelaySpin = QtWidgets.QSpinBox(self.angDelayFrame)
        self.angDelaySpin.setGeometry(QtCore.QRect(10, 50, 71, 24))
        self.angDelaySpin.setMaximum(1000)
        self.angDelaySpin.setObjectName("angDelaySpin")
        self.angCounterFrame = QtWidgets.QFrame(self.angPage)
        self.angCounterFrame.setGeometry(QtCore.QRect(600, 220, 91, 80))
        self.angCounterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.angCounterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.angCounterFrame.setObjectName("angCounterFrame")
        self.angCounterLabel = QtWidgets.QLabel(self.angCounterFrame)
        self.angCounterLabel.setGeometry(QtCore.QRect(10, 0, 61, 28))
        self.angCounterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.angCounterLabel.setObjectName("angCounterLabel")
        self.angCounterSpin = QtWidgets.QSpinBox(self.angCounterFrame)
        self.angCounterSpin.setGeometry(QtCore.QRect(10, 40, 71, 24))
        self.angCounterSpin.setMaximum(1000)
        self.angCounterSpin.setObjectName("angCounterSpin")
        self.angStateCombo = QtWidgets.QComboBox(self.angPage)
        self.angStateCombo.setGeometry(QtCore.QRect(610, 330, 81, 21))
        self.angStateCombo.setObjectName("angStateCombo")
        self.angStateCombo.addItem("")
        self.angNewStateBtn = QtWidgets.QPushButton(self.angPage)
        self.angNewStateBtn.setGeometry(QtCore.QRect(600, 370, 91, 32))
        self.angNewStateBtn.setObjectName("angNewStateBtn")
        self.angSubmitBtn = QtWidgets.QPushButton(self.angPage)
        self.angSubmitBtn.setGeometry(QtCore.QRect(600, 450, 91, 32))
        self.angSubmitBtn.setObjectName("angSubmitBtn")
        self.angSaveBtn = QtWidgets.QPushButton(self.angPage)
        self.angSaveBtn.setGeometry(QtCore.QRect(600, 410, 91, 32))
        self.angSaveBtn.setObjectName("angSaveBtn")
        self.angBaseLabel = QtWidgets.QLabel(self.angPage)
        self.angBaseLabel.setGeometry(QtCore.QRect(550, 40, 181, 61))
        self.angBaseLabel.setStyleSheet("font: 36pt \".SF NS Text\";")
        self.angBaseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.angBaseLabel.setObjectName("angBaseLabel")
        self.line = QtWidgets.QFrame(self.angPage)
        self.line.setGeometry(QtCore.QRect(510, 40, 20, 611))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayoutWidget_2.raise_()
        self.angDelayFrame.raise_()
        self.angCounterFrame.raise_()
        self.angCounterLabel.raise_()
        self.angCounterLabel.raise_()
        self.angStateCombo.raise_()
        self.angNewStateBtn.raise_()
        self.angSubmitBtn.raise_()
        self.angSaveBtn.raise_()
        self.angBaseLabel.raise_()
        self.line.raise_()
        self.stackedWidget.addWidget(self.angPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)

        # My Code Start

        #Changing Pages
        self.iKinBtn.clicked.connect(lambda : self.changePage(1))
        self.angBtn.clicked.connect(lambda : self.changePage(2))


        # My Code Finish
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def changePage(self, index):
        self.stackedWidget.setCurrentIndex(index)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.iKinBtn.setText(_translate("MainWindow", "Inverse Kinematic Base"))
        self.angBtn.setText(_translate("MainWindow", "Angle Base"))
        self.mainLabel.setText(_translate("MainWindow", "AUTMan Motion Editor"))
        self.stateCombo.setItemText(0, _translate("MainWindow", "State 1"))
        self.label.setText(_translate("MainWindow", "Inverse Kinematic Base"))
        self.lXLabel.setText(_translate("MainWindow", "L_Leg_Ik[I_X]"))
        self.lYLabel.setText(_translate("MainWindow", "L_Leg_Ik[I_Y]"))
        self.lZLabel.setText(_translate("MainWindow", "L_Leg_Ik[I_Z]"))
        self.lRollLabel.setText(_translate("MainWindow", "L_Leg_Ik[I_Roll]"))
        self.lPitchLabel.setText(_translate("MainWindow", "L_Leg_Ik[I_Pitch]"))
        self.lYawLabel.setText(_translate("MainWindow", "L_Leg_Ik[I_Yaw]"))
        self.rXLabel.setText(_translate("MainWindow", "R_Leg_Ik[I_X]"))
        self.rYLabel.setText(_translate("MainWindow", "R_Leg_Ik[I_Y]"))
        self.rZLabel.setText(_translate("MainWindow", "R_Leg_Ik[I_Z]"))
        self.rRollLabel.setText(_translate("MainWindow", "R_Leg_Ik[I_Roll]"))
        self.rPitchLabel.setText(_translate("MainWindow", "R_Leg_Ik[I_Pitch]"))
        self.rYawLabel.setText(_translate("MainWindow", "R_Leg_Ik[I_Yaw]"))
        self.lAPitchLabel.setText(_translate("MainWindow", "L_Arm[I_A_Pitch]"))
        self.lARollLabel.setText(_translate("MainWindow", "L_Arm[I_A_Roll]"))
        self.lAElbowLabel.setText(_translate("MainWindow", "L_Arm[I_A_Elbow]"))
        self.lAVpLabel.setText(_translate("MainWindow", "L_Arm[I_A_Vp]"))
        self.lAVrLabel.setText(_translate("MainWindow", "L_Arm[I_A_Vr] "))
        self.lAVeLabel.setText(_translate("MainWindow", "L_Arm[I_A_Ve]"))
        self.rAPitchLabel.setText(_translate("MainWindow", "R_Arm[I_A_Pitch]"))
        self.rARollLabel.setText(_translate("MainWindow", "R_Arm[I_A_Roll]"))
        self.rAElbowLabel.setText(_translate("MainWindow", "R_Arm[I_A_Elbow]"))
        self.rAVpLabel.setText(_translate("MainWindow", "R_Arm[I_A_Vp]"))
        self.rAVrLabel.setText(_translate("MainWindow", "R_Arm[I_A_Vr]"))
        self.rAVeLabel.setText(_translate("MainWindow", "R_Arm[I_A_Ve]"))
        self.delayLabel.setText(_translate("MainWindow", "Delay"))
        self.counterLabel.setText(_translate("MainWindow", "Counter"))
        self.newStateBtn.setText(_translate("MainWindow", "New Stage"))
        self.saveBtn.setText(_translate("MainWindow", "Save"))
        self.submitBtn.setText(_translate("MainWindow", "Submit"))
        self.label_2.setText(_translate("MainWindow", "Pan"))
        self.label_3.setText(_translate("MainWindow", "Tilt"))
        self.label_4.setText(_translate("MainWindow", "ShRR"))
        self.label_5.setText(_translate("MainWindow", "ShRL"))
        self.label_6.setText(_translate("MainWindow", "ShPL"))
        self.label_7.setText(_translate("MainWindow", "ShPR"))
        self.label_8.setText(_translate("MainWindow", "TP"))
        self.label_9.setText(_translate("MainWindow", "ShPL"))
        self.label_10.setText(_translate("MainWindow", "ShPR"))
        self.label_11.setText(_translate("MainWindow", "TP"))
        self.label_12.setText(_translate("MainWindow", "EPR"))
        self.label_13.setText(_translate("MainWindow", "TY"))
        self.label_14.setText(_translate("MainWindow", "EPL"))
        self.label_15.setText(_translate("MainWindow", "HYR"))
        self.label_21.setText(_translate("MainWindow", "HYL"))
        self.label_16.setText(_translate("MainWindow", "HPR"))
        self.label_22.setText(_translate("MainWindow", "HPL"))
        self.label_17.setText(_translate("MainWindow", "HRR"))
        self.label_23.setText(_translate("MainWindow", "HRL"))
        self.label_18.setText(_translate("MainWindow", "KPR"))
        self.label_24.setText(_translate("MainWindow", "KPL"))
        self.label_19.setText(_translate("MainWindow", "FPR"))
        self.label_25.setText(_translate("MainWindow", "FPL"))
        self.label_20.setText(_translate("MainWindow", "FRR"))
        self.label_26.setText(_translate("MainWindow", "FRL"))
        self.angDelayLabel.setText(_translate("MainWindow", "Delay"))
        self.angCounterLabel.setText(_translate("MainWindow", "Counter"))
        self.angStateCombo.setItemText(0, _translate("MainWindow", "State 1"))
        self.angNewStateBtn.setText(_translate("MainWindow", "New Stage"))
        self.angSubmitBtn.setText(_translate("MainWindow", "Submit"))
        self.angSaveBtn.setText(_translate("MainWindow", "Save"))
        self.angBaseLabel.setText(_translate("MainWindow", "Angle Base"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

